name: ğŸš€ Github Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4.1.1

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: ğŸ“¦ Install dependecies
        run: npm ci

      - name: ğŸ“ Run github release script
        run: npm run release:git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

